name: Build & Publish Docker image

on:
  push:
    tags:
      - '[1-9].*.*'

env:
  IMAGE_NAME: ghcr.io/finxico/fineract

permissions:
  contents: read
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: '**/build.gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0

      - name: Build & push with JIB
        run: |
          mvn compile \
            com.google.cloud.tools:jib-maven-plugin:3.3.1:build \
            -Dimage=${{ env.IMAGE_NAME }} \
            -Djib.to.tags=${{ github.ref_name }},latest \
            -Djib.to.auth.username=${{ github.actor }} \
            -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}

      - name: Log success
        run: echo "✔️ Imagen $IMAGE_NAME:${{ github.ref_name }} y :latest publicada en GHCR"